pageinfo = [[1248138148,939],
	[1271268940,12412],
	[1271269204,3133],
	[1248483575,3648],
	[1247785903,6206],
	[1324089098,188699],
	[1269036309,2706],
	[1269276643,3899],
	[1247786412,765],
	[1216740464,3751],
	[1228870868,1139],
	[1324089282,4400],
	[1271236486,146823],
	[1280184707,32211],
	[1269040663,4128],
	[1269037588,5100],
	[1280185124,15454],
	[1280185517,4959],
	[1280186035,17008],
	[1269041118,5334],
	[1269041118,3083],
	[1269041117,3272],
	[1271268717,6702],
	[1248388280,18160],
	[1269040380,2333],
	[1280188057,17414],
	[1268415721,14068],
	[1268414898,33679],
	[1247692173,6457],
	[1323999645,152006],
	[1248120485,812],
	[1269287802,7852],
	[1248120486,1827],
	[1228871094,1511],
	[1279658153,1902],
	[1280189930,14748],
	[1271268684,5673],
	[1248120486,4649],
	[1280183499,19225],
	[1248459490,1969],
	[1280191429,3976],
	[1280191057,46565],
	[1269041116,2013],
	[1269041115,4231],
	[1269041115,4839],
	[1269041115,4510],
	[1271236488,40908],
	[1255662420,28607],
	[1248481606,9053],
	[1255662433,1016],
	[1228871191,14141],
	[1255662440,21953],
	[1247766337,11983],
	[1248120489,2023],
	[1255662445,500],
	[1280252429,3531],
	[1269471368,14363],
	[1248481256,1829],
	[1255713340,9380],
	[1255662498,5055],
	[1217453892,670],
	[1271236489,1833],
	[1269041206,17750],
	[1248120491,1040],
	[1247777833,4626],
	[1247777981,4259],
	[1248113730,2931],
	[1248405270,12228],
	[1324074565,4835],
	[1324076671,3303],
	[1248120485,3050],
	[1247778183,2412],
	[1248406033,5689],
	[1268358500,4904],
	[1324079339,16446],
	[1280247356,4757],
	[1228871088,1775],
	[1271236488,51468],
	[1271268825,27141],
	[1324077009,2402],
	[1324076245,9578],
	[1324078165,3196],
	[1324075893,8324],
	[1324077883,10820]];
pagedata = [ ["about2.htm","About","Using the Help Files The help files are designed to familiarize users with the Cisco Packet Tracer interface, functions, and features. Although th...",""],
["translation.htm","Packet Tracer Translation Process","Packet Tracer Translation Process Packet Tracer supports semi-automated translation to all Unicode-supported languages. The first part of this gui...",""],
["acknowledgements.htm","Acknowledgements","Packet Tracer Development Packet Tracer Concept and Design Dennis Frezzo Michael Wang Mark Chen Brad Anderson Packet Tracer Team Project Manager: ...",""],
["activityWizard.htm","Activity Wizard","Activity Wizard The Activity Wizard is an assessment tool that allows you to create highly specific networking scenarios for other users. If you a...",""],
["activityWizard_answerNetwork.htm","Answer Network","Answer Network In the Answer Network panel, you construct the answer network, and mark the elements of the network on which you want to assess the...",""],
["activityWizard_assessmentItems.htm","Assessment Items","Assessment Items What are Assessment Items? The assessment items are found in the Assessment Items tab of the Answer Network section in the Activi...",""],
["activityWizard_initialNetwork.htm","Initial Network","Initial Network In the Initial Network panel, you set the network from which the user will start the activity. One option for setting up the initi...",""],
["activityWizard_instructions.htm","Instructions","Instructions The student instructions for the activity are entered in the Instructions panel. When students open the activity file, the instructio...",""],
["activityWizard_password.htm","Password","Password The Password panel allows you to set a password for the Activity Wizard features of the activity file. If no password is set, anyone who ...",""],
["activityWizard_run.htm","Running Activity Files","Running Activity Files You start an activity by opening a saved activity (.pka) file. You will first see the Instructions window telling you how t...",""],
["activityWizard_test.htm","Testing/Checking the Activity (Previewing)","Testing/Checking the Activity (Previewing) When you choose the Test Activity tab from the Activity Menu, you can do a trial run of the activity yo...",""],
["activityWizard_variableManager.htm","Variable Manager","Variable Manager In the Variable Manager panel , you will be able to add dynamism to activities. Numbers, strings, and IP addresses may be assigne...",""],
["CLI_routerIOS.htm","Cisco IOS Supported Commands: Routers","Routers: IOS Packet Tracer uses a simplified model of the Cisco IOS. Click on the CLI tab in the router configuration window to access the Cisco I...",""],
["CLI_switchIOS.htm","Cisco IOS Supported Commands: Switches","Switches: IOS Packet Tracer uses a simplified model of the Cisco IOS. Click on the CLI tab in the switch configuration window to access the Cisco ...",""],
["config_clouds.htm","Configuring Clouds","Configuring Clouds The Config tab offers three general levels of configuration: global, connections, and interface. To configure at the global lev...",""],
["config_others.htm","Configuring Other Devices","Configuring Other Devices The configuration options for all other devices are relatively simple. In general, you can change their display names in...",""],
["config_PCs.htm","Configuring PCs","Configuring PCs, Laptops, Tablet PCs, and PDAs You can configure the global settings and interface settings on the PC, laptop, tablet PC, and PDA ...",""],
["config_routers.htm","Configuring Routers","Configuring Routers The Config tab offers four general levels of configuration: global, routing, switching (Cisco 1841 and Cisco 2811 only), and i...",""],
["config_servers.htm","Configuring Servers","Configuring Servers The Config tab offers three general levels of configuration: global, services, and interface. To configure at the global level...",""],
["config_switches.htm","Configuring Switches","Configuring Switches The Config tab for the switch offers three general levels of configuration: global, switching, and interface. The global leve...",""],
["config_wrt300n.htm","Configuring Linksys WRT300N","Configuring Linksys WRT300N The Config tab offers two general levels of configuration: global and interface. To configure at the global level, cli...",""],
["configuringDevices.htm","Configuring Devices","Configuring Devices As with real networks, the networks you make in Packet Tracer must be properly configured before they \"work.\" For simple devic...",""],
["connectionsLinks.htm","Connections / Links","Connections / Links Packet Tracer supports a wide range of network connections. Each cable type can only be connected to certain interface types. ...",""],
["copyrights.htm","Copyrights","Cisco Packet Tracer Software License Agreement IMPORTANT: PLEASE READ THIS CISCO PACKET TRACER SOFTWARE LICENSE AGREEMENT (THE ‚&#128;úAGREEMENT‚&#128;ù) CA...",""],
["devicesAndModules.htm","Devices and Modules","Devices and Modules Packet Tracer supports a wide array of modules for networking devices. To change a module in any device, you must first turn o...",""],
["devicesAndModules_endDevices.htm","Devices and Modules: End Devices","Devices and Modules: End Devices All images on this page are thumbnails in which you can click to bring up a larger image. PC-PT The PC-PT provide...",""],
["devicesAndModules_others.htm","Devices and Modules: Other Devices","Devices and Modules: Other Devices All images on this page are thumbnails on which you can click to bring up a larger image. Hub-PT The Hub-PT pro...",""],
["devicesAndModules_routers.htm","Devices and Modules: Routers","Devices and Modules: Routers All images on this page are thumbnails on which you can click to bring up a larger image. Router: 1841 The Cisco 1841...",""],
["devicesAndModules_switches.htm","Devices and Modules: Switches","Devices and Modules: Switches All images on this page are thumbnails on which you can click to bring up a larger image. Switch: 2950-24 The Cisco ...",""],
["faqTroubleShoot.htm","Frequently Asked Questions (FAQ)/Troubleshoot Guide","Frequently Asked Questions (FAQ)/Troubleshooting Guide General Issues 1. My computer frequently crashes when I use Packet Tracer. 2. The program s...",""],
["gettingStarted.htm","Getting Started","Getting Started The best place to get started is to review the help files. The help files contain comprehensive documentation on almost all the fe...",""],
["GUI_wrt300n.htm","Linksys WRT300N: GUI","Linksys WRT300N: GUI The GUI tab offers the same configurations and settings as the Config tab with some additional features for access restrictio...",""],
["sampleFilesAndDesignPatterns_design.htm","Design Challenges","Design Challenges Design challenges are constraint-based problems with multiple correct solutions. They may range from very simple (devise a class...",""],
["sampleFilesAndDesignPatterns_troubleshoot.htm","Troubleshooting","Troubleshooting Troubleshooting activities include diagnosing, isolating, and fixing the simulated network from a previously bugged network file. ...",""],
["systemRequirements.htm","System Requirements","System Requirements Minimum CPU: Intel Pentium III 500 MHz or equivalent OS: Microsoft Windows XP, Microsoft Windows Vista, Microsoft Windows 7, F...",""],
["interfaceOverview.htm","Interface Overview","Interface Overview When you open Packet Tracer, by default you will be presented with the following interface: This initial interface contains ten...",""],
["intro.htm","Introduction","Introduction Welcome to Cisco Packet Tracer. Packet Tracer is a medium fidelity, network-capable, simulation-based learning environment for networ...",""],
["ipc.htm","IPC","IPC (Inter-Process Communication) The IPC (Inter-Process Communication) feature controls an external programming extension for Packet Tracer that ...",""],
["keyboardShortcuts.htm","Keyboard Shortcuts","Keyboard Shortcuts Many actions in Packet Tracer are keyboard-accessible for your convenience. In addition to key combinations, the following keys...",""],
["sampleFilesAndDesignPatterns.htm","Sample Files, File Compatibility, and Design Patterns","Sample Files, File Compatibility, and Design Patterns There are over 300 Packet Tracer .pka files that exist embedded in the Discovery and Explora...",""],
["mode_realtime.htm","Realtime Mode","Realtime Mode In Realtime Mode, your network is always running (like a real network) whether you are working on the network or not. Your configura...",""],
["mode_simulation.htm","Simulation Mode","Simulation Mode In Simulation Mode, you can watch your network run at a slower pace, observing the paths that packets take and inspecting them in ...",""],
["mode_simulation_complexPDUs.htm","Simulation Mode: Complex PDUs","Simulation Mode: Complex PDUs In addition to simple, quick pings, you can also send customized PDUs. In the Common Tools Bar, click the Add Comple...",""],
["mode_simulation_PDUinfo.htm","Simulation Mode: PDU Information","Simulation Mode: PDU Information During a simulation, you can click on a packet (on the topology or the corresponding event in the Event List) to ...",""],
["mode_simulation_Scenarios.htm","Simulation Mode: Managing Simulation Scenarios","Simulation Mode: Managing Simulation Scenarios In Packet Tracer, you can set up and simulate complex networking situations (scenarios) through the...",""],
["mode_simulation_specialNotes.htm","Simulation Mode: Special Notes","Simulation Mode: Special Notes Editing the Network and Using the Cisco IOS in Simulation Mode Although Realtime Mode is the preferred mode for net...",""],
["model_layer2.htm","Layer 2 Models","Layer 2 Models How switches process incoming frames When a switch receives a frame ( flowchart here): It compares the receiving port&#39;s type (trunk...",""],
["model_layer3IP.htm","Layer 3 IP Models","Layer 3 IP Models How IP and IPv6 are modeled Packet Tracer models only certain aspects of IP. IP version 4 is modeled. IP addresses are 32 bits l...",""],
["model_layer4.htm","Layer 4 Models","Layer 4 Models How devices process UDP segments This procedure explains how a device sends and receives UDP segments. When the device receives a s...",""],
["modeling.htm","Modeling in Packet Tracer","Modeling in Packet Tracer Packet Tracer simulates the behavior of real networks and devices using models. As with all simulations, the program is ...",""],
["model_misc.htm","Other Models","Other Models How routers process incoming packets (NAT process) When a router receives a packet: It checks if the receiving port is a NAT outside ...",""],
["myFirstPTLab.htm","My First Packet Tracer Lab","My First Packet Tracer Lab Introduction Welcome to Packet Tracer. Research has shown that users who master a few basic tasks when first starting t...",""],
["multiuser.htm","Multiuser","Multiuser Multiuser communication allows multiple point-to-point (peer) connections between multiple instances of Packet Tracer. By allowing commu...",""],
["operatingModes.htm","Operating Modes","Operating Modes Packet Tracer operating modes reflect the network time scheme. In Realtime Mode, your network runs in a model of real time, within...",""],
["support.htm","Packet Tracer Support and Contact Information","Packet Tracer Support and Contact Information Please visit the Academy Connection website and its community forums for peer support. ",""],
["search.html","Search","Search Enter keyword(s) to search. ",""],
["timeConstants.htm","Time Constants","Time Constants Packet Tracer uses the following time constants: RIP/RIPv6 default update 30 secs RIP/RIPv6 default timeout 3 mins RIP/RIPv6 defaul...",""],
["model_layer1.htm","Layer 1 Models","Layer 1 Models How hubs process frames When a hub receives a frame ( flowchart here): If two or more ports receive frames at the same time, a coll...",""],
["tutorials.htm","Tutorials","Tutorials The following tutorials demonstrate the basic functions, features, and aspects of Packet Tracer. Although you can view them at any time,...",""],
["usesForPT.htm","Uses for Packet Tracer","Uses for Packet Tracer For Students Welcome to the world of computer networking. Packet Tracer can be a fun, take-home, flexible piece of software...",""],
["tutorials_stub.htm","Tutorials","Tutorials The tutorial package is not installed. To view the tutorials, download the Packet Tracer tutorial package from Academy Connection and in...",""],
["whatsNew.htm","What&#39;s New","What&#39;s New Users of previous versions of Packet Tracer will note a variety of new features in this version of Packet Tracer. Protocol Improvements...",""],
["workspace_logical.htm","The Logical Workspace","The Logical Workspace The Logical Workspace is where you will spend the majority of your time building and configuring your network. In conjunctio...",""],
["workspaceBasics.htm","The Logical and Physical Workspaces","The Logical and Physical Workspaces Packet Tracer uses two representation schemes for your network: the Logical Workspace and the Physical Workspa...",""],
["workspace_physical.htm","The Physical Workspace","The Physical Workspace The purpose of the Physical Workspace is to give a physical dimension to your logical network topology. It gives you a sens...",""],
["workspace_physical_movingDevices.htm","The Physical Workspace: Moving Devices","The Physical Workspace: Moving Devices The Physical Workspace allows you to move your devices to various locations. To do this click on the Move O...",""],
["workspace_physical_specialNotes.htm","The Physical Workspace: Special Notes","The Physical Workspace: Special Notes Navigation Panel You can click on the Navigation button from the Physical Workspace Bar to bring up the navi...",""],
["model_layer5.htm","Layer 5 Models","Layer 5 Models How Routers Handle ISAKMP Segments When a router sends an ISAKMP segment ( flowchart here): If a packet is getting out of the devic...",""],
["scriptModules.htm","Script Modules","Script Modules Script Modules are independent entities that add new functionality to Packet Tracer similar to External Applications (ExApps). But ...",""],
["scriptModules_customUdp.htm","Script Modules","Script Modules - Custom UDP Processes With Script Modules, instructors and students can now develop and add new protocols to PT. They are called c...",""],
["sampleFilesAndDesignPatterns_conceptBuilder.htm","Concept Builders","Concept Builders Concept builders are model-building inquiries and investigations leading to student-created explanations and animations of networ...",""],
["workspace_physical_distanceMeasurements.htm","The Physical Workspace: Distance Measurements","The Physical Workspace: Distance Measurements The Physical Workspace provides the dimension of distance to Ethernet and wireless devices. This dis...",""],
["workspace_physical_cableManipulation.htm","The Physical Workspace: Cable Manipulation","?The Physical Workspace: Cable Manipulation In Physical Workspace, cables can be manipulated to provide a more realistic representation of a physi...",""],
["workspace_physical_customIconsAndBG.htm","The Physical Workspace: Moving Devices","The Physical Workspace: Customizing Icons and Backgrounds (BG) Using Custom Icons Icons that represent devices in Packet Tracer in both Logical an...",""],
["activityWizard_scoringModelAndScripting.htm","Scoring Model/Scripting","Scoring Model/Scripting The Scoring Model is an Evidence Centered Design process by which to assess work products through the application of scori...",""],
["workspace_logical_customIconsAndBG.htm","The Physical Workspace: Moving Devices","The Logical Workspace: Customizing Icons and Backgrounds (BG) Using Custom Icons Icons that represent devices in Packet Tracer in both Logical and...",""],
["sampleFilesAndDesignPatterns_skillBuilder.htm","Skill Builders","Skill Builders Skill builders support algorithmic problem solving in support of the development of networking procedural knowledge. For example, s...",""],
["model_layer7.htm","Layer 7 Models","Layer 7 Models How DHCP clients process incoming packets When a DHCP client device receives a packet: It drops the packet if (any): The packet is ...",""],
["model_layer3Routing.htm","Layer 3 Routing Models","Layer 3 Routing Models - RIPv1 RIPv2 EIGRP OSPF How a router starts the RIP process The router generates a RIP request packet to be sent out all p...",""],
["scriptModules_dataStore.htm","Script Modules","Script Modules - Data Store The data store is the other part of the model in the Script Module. The data store has a list of data files, in json, ...",""],
["scriptModules_scriptEngine.htm","Script Modules","Script Modules - Script Engine Each Script Module has one instance of a Qt Script Engine. A Script Module can contain multiple script files writte...",""],
["scriptModules_tips.htm","Script Modules","Script Modules - Tips The dprint() function is per Script Module. Check the Debug Dialog of the correct Script Module for these outputs. Changes m...",""],
["scriptModules_scriptingInterface.htm","Script Modules","Script Modules - Scripting Interface The Scripting Interface is the Script Module development environment inside PT. This is extended from the Scr...",""],
["scriptModules_webViews.htm","Script Modules","Script Modules - Web Views Web Views Web views are using the QtWebKit functionality to render HTML5. Script Modules use web views to create custom...",""]];
